#!/usr/bin/ruby

lines = File.readlines 'Font-Awesome/less/icons.less'
icons = lines.select { |line| line.start_with? ".@{fa-css-prefix}" }
icons = icons.map {|icon|
    icon =~ /\.@\{fa-css-prefix\}-([^:]+):before/
    $1
}
puts icons

File.open("cheatsheet.html", "w") { |out|
	out.puts <<EOS
<!-- Generated by Font Awesome cheatsheet generator by Michal Pokorny -->
<!-- http://github.com/MichalPokorny/Font-Awesome-cheatsheet -->
<!DOCTYPE html>
<html>
	<head>
		<title>Font Awesome cheatsheet</title>
		<link rel="stylesheet" href="Font-Awesome/css/font-awesome.css">
		<link rel="stylesheet" href="cheatsheet.css">
	</head>

	<body>
		<ul>
EOS
	for icon in icons
		out.puts "\t\t\t<li><div><i class=\"fa fa-#{icon}\"></i></div><div>#{icon.sub "icon-", ""}</div></li>"
	end
	out.puts <<EOS
		</ul>
	</body>
</html>
EOS
}

